// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  capabilities

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CertificateVerificationRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CertificateVerificationRequest ) UnmarshalJSON([]byte) error { return nil }
func ( CertificateVerificationRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CertificateVerificationRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CertificateVerificationRequest *CertificateVerificationRequest

func ( CertificateVerificationResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CertificateVerificationResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CertificateVerificationResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CertificateVerificationResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CertificateVerificationResponse *CertificateVerificationResponse

func ( GetResourceRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetResourceRequest ) UnmarshalJSON([]byte) error { return nil }
func ( GetResourceRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetResourceRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetResourceRequest *GetResourceRequest

func ( KeylessInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* KeylessInfo ) UnmarshalJSON([]byte) error { return nil }
func ( KeylessInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* KeylessInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_KeylessInfo *KeylessInfo

func ( KeylessPrefixInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* KeylessPrefixInfo ) UnmarshalJSON([]byte) error { return nil }
func ( KeylessPrefixInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* KeylessPrefixInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_KeylessPrefixInfo *KeylessPrefixInfo

func ( ListAllResourcesRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ListAllResourcesRequest ) UnmarshalJSON([]byte) error { return nil }
func ( ListAllResourcesRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ListAllResourcesRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ListAllResourcesRequest *ListAllResourcesRequest

func ( ListResourcesByNamespaceRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ListResourcesByNamespaceRequest ) UnmarshalJSON([]byte) error { return nil }
func ( ListResourcesByNamespaceRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ListResourcesByNamespaceRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ListResourcesByNamespaceRequest *ListResourcesByNamespaceRequest

func ( LookupHostResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LookupHostResponse ) UnmarshalJSON([]byte) error { return nil }
func ( LookupHostResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LookupHostResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LookupHostResponse *LookupHostResponse

func ( OciManifestResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* OciManifestResponse ) UnmarshalJSON([]byte) error { return nil }
func ( OciManifestResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* OciManifestResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OciManifestResponse *OciManifestResponse

func ( VerificationResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* VerificationResponse ) UnmarshalJSON([]byte) error { return nil }
func ( VerificationResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* VerificationResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VerificationResponse *VerificationResponse

func ( sigstoreCertificateVerify ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstoreCertificateVerify ) UnmarshalJSON([]byte) error { return nil }
func ( sigstoreCertificateVerify ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstoreCertificateVerify ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstoreCertificateVerify *sigstoreCertificateVerify

func ( sigstoreGithubActionsVerifyV2 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstoreGithubActionsVerifyV2 ) UnmarshalJSON([]byte) error { return nil }
func ( sigstoreGithubActionsVerifyV2 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstoreGithubActionsVerifyV2 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstoreGithubActionsVerifyV2 *sigstoreGithubActionsVerifyV2

func ( sigstoreKeylessPrefixVerifyV2 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstoreKeylessPrefixVerifyV2 ) UnmarshalJSON([]byte) error { return nil }
func ( sigstoreKeylessPrefixVerifyV2 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstoreKeylessPrefixVerifyV2 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstoreKeylessPrefixVerifyV2 *sigstoreKeylessPrefixVerifyV2

func ( sigstoreKeylessVerify ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstoreKeylessVerify ) UnmarshalJSON([]byte) error { return nil }
func ( sigstoreKeylessVerify ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstoreKeylessVerify ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstoreKeylessVerify *sigstoreKeylessVerify

func ( sigstoreKeylessVerifyRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstoreKeylessVerifyRequest ) UnmarshalJSON([]byte) error { return nil }
func ( sigstoreKeylessVerifyRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstoreKeylessVerifyRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstoreKeylessVerifyRequest *sigstoreKeylessVerifyRequest

func ( sigstoreKeylessVerifyV2 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstoreKeylessVerifyV2 ) UnmarshalJSON([]byte) error { return nil }
func ( sigstoreKeylessVerifyV2 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstoreKeylessVerifyV2 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstoreKeylessVerifyV2 *sigstoreKeylessVerifyV2

func ( sigstorePubKeysVerify ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstorePubKeysVerify ) UnmarshalJSON([]byte) error { return nil }
func ( sigstorePubKeysVerify ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstorePubKeysVerify ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstorePubKeysVerify *sigstorePubKeysVerify

func ( sigstorePubKeysVerifyRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstorePubKeysVerifyRequest ) UnmarshalJSON([]byte) error { return nil }
func ( sigstorePubKeysVerifyRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstorePubKeysVerifyRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstorePubKeysVerifyRequest *sigstorePubKeysVerifyRequest

func ( sigstorePubKeysVerifyV2 ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* sigstorePubKeysVerifyV2 ) UnmarshalJSON([]byte) error { return nil }
func ( sigstorePubKeysVerifyV2 ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* sigstorePubKeysVerifyV2 ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_sigstorePubKeysVerifyV2 *sigstorePubKeysVerifyV2
