name: CI

on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.15'
      - run: make test
